### ISSUE TITLE
findnonltrs failed

### ISSUE THREAD

**Issue by altingia** [sestaton/tephra#22]
ERROR: Could not open file: /home/altingia/software/tephra-0.09.6/t/test_data/ref_tephra_masked4_nonLTRs/b/out2/full at /home/altingia/anaconda2/lib/perl5/site_perl/5.22.0/Tephra/NonLTR/Postprocess.pm line 69.

**Comment by sestaton** [comment]
Hi,

It would help if you could provide some more details. Please indicate your OS and what command you are trying to run. Also, what series of commands led to the error message?

Thanks.

**Comment by altingia** [comment]
Dear sestaton,
Thanks for your help. I  compiled the tephra v0.9.0 on the Ubunut 16.04 LTS , and run the command 'tephra all -c tephra_myconfigure.yml'; All other subcommands were successful, but failed at the subcommand 'findnonltrs' as following:

INFO - Command - 'tephra findnonltrs' started at:   17-12-2017 06:33:16.
DEBUG:  tephra findnonltrs -g /home/altingia/data/genomes/Melc/Melc_scaffolds_masked4.fasta -o /home/altingia/data/genomes/Melc/Melc_scaffolds_nonLTRs.gff3

ERROR: Could not open file: /home/altingia/data/genomes/Melc/Melc_scaffolds_masked4_nonLTRs/b/out2/full at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Tephra/NonLTR/Postprocess.pm line 69.
INFO - Command - 'tephra findnonltrs' completed at: 17-12-2017 07:31:29. Final output files:
INFO - Output files - /home/altingia/data/genomes/Melc/Melc_scaffolds_nonLTRs.gff3
INFO - Output files - /home/altingia/data/genomes/Melc/Melc_scaffolds_nonLTRs.fasta.
and I didn't find the two results file: Melc_scaffolds_nonLTRs.gff3 and Melc_scaffolds_nonLTRs.fasta.

**Comment by sestaton** [comment]
Hi @altingia,

Sorry for the delay, I've been away from the office on a couple of trips this month. Could you privately send me a link to the genome file for testing (or share it somehow)? I'd like to follow up with this and determine if this is a bug or some other kind of issue that can be handled and reported in a better way.

Thanks, Evan

**Comment by sestaton** [comment]
I've made a new release that fixes this issue (version 0.09.8). Now warnings will be issued when no non-LTR elements are found. If you think there should be non-LTR elements found please check the input and comment below. I can reopen this issue or open a new one if you still have problems with the command. Thanks for reporting.
