### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by ShowkyBioinformatics** [sestaton/tephra#25]
When i run the tephra to indentify the TE on a new genome, and i had faild with the following problems:
Use of uninitialized value $chromosome in concatenation (.) or string at lib/site_perl/5.14.0/Tephra/Role/Util.pm line 41.
Use of uninitialized value $start in concatenation (.) or string at lib/site_perl/5.14.0/Tephra/Role/Util.pm line 41.
Use of uninitialized value $end in concatenation (.) or string at lib/site_perl/5.14.0/Tephra/Role/Util.pm line 41.

[ERROR]: Something went wrong fetching sequence for ':-'. Got zero length.
 at lib/site_perl/5.14.0/Tephra/Genome/Unmask.pm line 78.

**Comment by sestaton** [comment]
I would need to see your configuration file and/or the command you used to diagnose this message.

Though, I suspect you have weird symbols in your sequence name such as ":" and "-" or similar. Can you confirm this or comment further?

Thanks.

**Comment by sestaton** [comment]
Hi again,

Could you please provide an update? Without some understanding of the input or the command that was given there is no way to debug the error.

Also, I made a new major release yesterday with lots of changes. If you can, give that new version (v0.12.0) a try and see if that solves the problem.

Thanks.
