### ISSUE TITLE
Problems running

### ISSUE THREAD

**Issue by juancresc** [sestaton/tephra#30]
Installed everything as required (and a few more perl libs) and now I get the following. Seems like a problem with Bio/DB/HTS specifically, I installed htslib as required and the module manually. 

tephra all -c tephra_config.yml
Can't load '/usr/local/lib/x86_64-linux-gnu/perl/5.22.1/auto/Bio/DB/HTS/HTS.so' for module Bio::DB::HTS: libhts.so.2: cannot open shared object file: No such file or directory at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
Compilation failed in require at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
BEGIN failed--compilation aborted at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Bio/DB/HTS/Kseq.pm line 71.
Compilation failed in require at /usr/local/share/perl/5.22.1/Tephra/Stats/Age.pm line 17.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/Tephra/Stats/Age.pm line 17.
Compilation failed in require at /usr/local/share/perl/5.22.1/Tephra/Command/age.pm line 11.
BEGIN failed--compilation aborted at /usr/local/share/perl/5.22.1/Tephra/Command/age.pm line 11.
Compilation failed in require at /usr/local/share/perl/5.22.1/App/Cmd.pm line 194.
        App::Cmd::_command("Tephra", HASH(0x1374f30)) called at /usr/local/share/perl/5.22.1/App/Cmd.pm line 171
        App::Cmd::new("Tephra", HASH(0x1374f30)) called at /usr/local/bin/tephra

**Comment by sestaton** [comment]
Can you share the commands you used to install? That would help diagnose the issue.

Thanks.

**Comment by juancresc** [comment]
The issue was because I installed  htslib 1.9 and 1.6, but 1.5 was required for Bio::DB::HTS-

```
wget https://github.com/samtools/htslib/archive/1.5.zip
unzip 1.5.zip
cd htslib-1.5/
sudo make install
ldconfig
```
and then 
`cpan Bio::DB::HTS`

**Comment by sestaton** [comment]
Thanks for the feedback. I'm using an earlier version of htslib (v1.3.1), but I will test with later versions.

Ideally, I'd suggest using the automated install route because it is tested and will be easier to tune, whereas custom/manual installs are more difficult to debug.
