### ISSUE TITLE
manual installation: missing modules for cpan in docs

### ISSUE THREAD

**Issue by juancresc** [sestaton/tephra#31]
I've installed tephra manually, maybe I did something wrong or missed something, but i had to install many modules and libs for using it:

sudo apt-get install libmoosex-perl libpath-class-perl libgsl-dev libmoose-perl
cpan Parallel::ForkManager
cpan  Bio::GFF3::LowLevel
cpan YAML::Tiny
cpan Bio::DB::HTS::Kseq
cpan Log::Log4perl
cpan App::Cmd
cpan Path::Class
cpan Log::Any
cpan DateTime
cpan Lingua::EN::Inflect
cpan List::UtilsBy
cpan Number::Range
cpan Set::IntervalTree
cpan Log::Any::Adapter::Log4perl

I've also had a hard time installing htslib. This is why I'd suggest to use the docker option (in our case it was not possible at the time)

**Comment by sestaton** [comment]
Hi,

There is no need to install anything manually in this fashion. As per the [install docs](https://github.com/sestaton/tephra/blob/master/INSTALL.md), you can just type:

    cpanm --installdeps .

And that will take care of the dependencies. Concerning HTSlib, you don't need to install this manually. When you run "perl Makefile.PL" this should be handled for you. 

If you ran those commands, did you find that the installation was broken after you ran `make test`?

**Comment by sestaton** [comment]
I should note that a working C compiler and the program `make` are required to build from source, among some other core libraries. This may have been part of the issue.

**Comment by juancresc** [comment]
thank you for the clarification. I missed that command

**Comment by sestaton** [comment]
No worries, thank you for the response. I know there are quite a few dependencies but I've tried to make it as automated as possible. 

Let me know if you have any further questions.
