### ISSUE TITLE
Can we run the command LTR age for our own files

### ISSUE THREAD

**Issue by juancresc** [sestaton/tephra#34]
We have a .fasta file containing LTRs and would like to run the age command on that file, but I cannot see in the docs how to do so.

thanks!

**Comment by sestaton** [comment]
Hi,

Sorry for the delay! The short answer is "no"; you must provide a SO-compliant GFF3 file and a genome file to pull the sequences. 

I suppose providing a FASTA would be possible but then the IDs would have to be formatted correctly beforehand for the process to work with MUSCLE and PAML, and this is the tricky part that I've put a lot of time into solving. 

It would probably take too much time and work to allow arbitrary FASTA IDs, so for now, I'm going to recommend providing the GFF3 file. If this becomes a common request, or is useful in general, we can  revisit the issue.

Thanks.
