### ISSUE TITLE
singularity container doesn't contain perldoc

### ISSUE THREAD

**Issue by nhartwic** [sestaton/tephra#44]
Not sure if this is intended or not, but using the -m flag fails as a result of perl-doc not being installed inside the container.

Steps to reproduce...
```
singularity pull library://sestaton/default/tephra
singularity exec tephra_latest.sif tephra all -m
```

**Comment by sestaton** [comment]
Thank you for the notice. I've updated the images and it should work know. Please note the command in the README file for starting the container.

**Comment by sestaton** [comment]
Closing this old issue. Please update if you have more issues with the latest version (v0.13.0).
