### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by altingia** [sestaton/tephra#45]
[ERROR]: LTR_retrotransposon1587_scaffold not found in store of Tephra::Classify::Fams::make_fasta_from_dom_orgs. This is a bug, please report it.

**Comment by sestaton** [comment]
Hi, can you try the latest version (v0.12.6) and let me know if this is still an issue? Thanks.

**Comment by sestaton** [comment]
Latest version is now v0.13.0. If the issue remains please update this post with more information and I will try to help. Closing for now.
